<?php

namespace app\lib\exception;


use think\Exception;
use think\exception\Handle;

class ExceptionHandler extends Handle{
    public function render(Exception $e) {
//        return parent::render($e+"wewe"); // TODO: Change the autogenerated stub

        return json(["error"=>"90```----"]);
    }
}